version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: habitapp
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: "app:create_app"
      FLASK_DEBUG: "1"
      FLASK_RUN_HOST: "0.0.0.0"
      FLASK_RUN_PORT: "5000"
      RESEND_API_KEY: my_resend_api_key_here
